# Generated by Django 4.2.29 on 2026-04-02 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectThread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_group', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'instagram_direct_threads',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('carousel', 'Carousel')], default='image', max_length=20)),
                ('urls', models.JSONField(default=dict)),
                ('caption', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('like_count', models.IntegerField(default=0)),
                ('comment_count', models.IntegerField(default=0)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ig_media', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'instagram_media',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('usage_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_url', models.URLField()),
                ('expires_at', models.DateTimeField()),
                ('view_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ig_stories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'instagram_stories',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('follow', 'Follow'), ('mention', 'Mention'), ('dm', 'DM')], max_length=20)),
                ('ref_type', models.CharField(blank=True, max_length=20)),
                ('ref_id', models.UUIDField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ig_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'instagram_notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DirectMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField(blank=True)),
                ('media_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ig_dm_sent', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ig_messages', to='instagram.directthread')),
            ],
            options={
                'db_table': 'instagram_direct_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ig_comments', to='instagram.media')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ig_replies', to='instagram.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ig_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'instagram_comments',
            },
        ),
        migrations.CreateModel(
            name='MediaTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='instagram.media')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='instagram.tag')),
            ],
            options={
                'db_table': 'media_tags',
                'unique_together': {('media', 'tag')},
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ig_likes', to='instagram.media')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ig_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'instagram_likes',
                'unique_together': {('user', 'media')},
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('requested', 'Requested'), ('blocked', 'Blocked')], default='accepted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('followee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ig_followers', to=settings.AUTH_USER_MODEL)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ig_following', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'instagram_follows',
                'unique_together': {('follower', 'followee')},
            },
        ),
        migrations.CreateModel(
            name='DirectParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('member', 'Member'), ('admin', 'Admin')], default='member', max_length=20)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ig_participants', to='instagram.directthread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ig_dm_participants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'instagram_direct_participants',
                'unique_together': {('thread', 'user')},
            },
        ),
    ]
